// Auto-generated by Supabase CLI: npx supabase gen types typescript --local > src/types/database.ts
// Run this command after setting up your database schema.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      stripe_connections: {
        Row: {
          id: string;
          user_id: string;
          status: string;
        };
        Insert: Record<string, unknown>;
        Update: Record<string, unknown>;
      };
      metrics_snapshots: {
        Row: {
          id: string;
          connection_id: string;
          snapshot_date: string;
          mrr: number;
          active_customers: number;
          churn_rate: number;
          nrr: number;
        };
        Insert: Record<string, unknown>;
        Update: Record<string, unknown>;
      };
      revenue_leaks: {
        Row: {
          id: string;
          connection_id: string;
          status: string;
          category: string;
          severity: string;
          title: string;
          lost_revenue: number;
          recoverable_revenue: number;
        };
        Insert: Record<string, unknown>;
        Update: Record<string, unknown>;
      };
      [key: string]: {
        Row: Record<string, unknown>;
        Insert: Record<string, unknown>;
        Update: Record<string, unknown>;
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
