-- Migration 005: Align local migrations with production schema.
--
-- Generated by `supabase db diff --linked` on 2026-05-02 to capture ~23 tables,
-- 12 functions, 78 indexes, 7 policies, 3 triggers, and many constraints that
-- had accumulated in production via the Supabase Studio UI without ever being
-- captured in a migration file. This migration brings the sequential `001`-`005`
-- chain back in sync with what production actually looks like, so a fresh
-- `supabase db push` against an empty project reproduces production end-to-end.
--
-- This file is idempotent for the trivial cases (CREATE TABLE / INDEX / TRIGGER /
-- POLICY all guarded by IF NOT EXISTS or DROP IF EXISTS). The 96 `add constraint`
-- statements are NOT idempotent — they will fail if reapplied to a database
-- where the constraints already exist. To prevent this on the existing
-- production database (where everything already exists), this migration must be
-- marked as already applied via:
--
--   npx supabase migration repair --status applied 005
--
-- After repair, `db push` skips this migration on production while still
-- replaying it on fresh environments.

drop extension if exists "pg_net";

drop index if exists "public"."idx_usage_events_ai_query";


  create table if not exists "public"."analytics_events" (
    "id" uuid not null default gen_random_uuid(),
    "user_id" uuid,
    "event_name" text not null,
    "event_category" text,
    "event_data" jsonb,
    "page_path" text,
    "referrer" text,
    "user_agent" text,
    "ip_address" text,
    "created_at" timestamp with time zone default now()
      );



  create table if not exists "public"."api_usage" (
    "id" uuid not null default gen_random_uuid(),
    "user_id" uuid,
    "endpoint" text not null,
    "method" text not null,
    "status_code" integer,
    "response_time_ms" integer,
    "credits_used" integer default 1,
    "ip_address" text,
    "user_agent" text,
    "created_at" timestamp with time zone default now()
      );



  create table if not exists "public"."churn_interventions" (
    "id" uuid not null default gen_random_uuid(),
    "churn_prediction_id" uuid,
    "stripe_connection_id" uuid,
    "customer_id" text not null,
    "intervention_type" text not null,
    "intervention_description" text,
    "email_sent" boolean default false,
    "email_opened" boolean default false,
    "email_clicked" boolean default false,
    "offer_type" text,
    "offer_value" text,
    "offer_accepted" boolean default false,
    "offer_accepted_at" timestamp with time zone,
    "customer_retained" boolean,
    "mrr_saved" numeric(10,2),
    "retention_duration_days" integer,
    "actioned_by" uuid,
    "actioned_at" timestamp with time zone default now(),
    "notes" text,
    "metadata" jsonb default '{}'::jsonb,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."churn_interventions" enable row level security;


  create table if not exists "public"."churn_predictions" (
    "id" uuid not null default gen_random_uuid(),
    "stripe_connection_id" uuid,
    "customer_id" text not null,
    "subscription_id" text not null,
    "risk_score" numeric(5,2) not null,
    "risk_level" text not null,
    "churn_probability" numeric(5,2) not null,
    "predicted_churn_date" date,
    "mrr_at_risk" numeric(10,2) default 0,
    "ltv_at_risk" numeric(10,2) default 0,
    "risk_factors" jsonb default '[]'::jsonb,
    "signals" jsonb default '{}'::jsonb,
    "recommended_actions" jsonb default '[]'::jsonb,
    "generated_email_subject" text,
    "generated_email_body" text,
    "email_tone" text default 'professional'::text,
    "status" text default 'pending'::text,
    "actioned_at" timestamp with time zone,
    "actioned_by" uuid,
    "outcome" text,
    "outcome_notes" text,
    "model_version" text default 'v1.0'::text,
    "confidence_score" numeric(5,2),
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now()
      );


alter table "public"."churn_predictions" enable row level security;


  create table if not exists "public"."churn_prevention_settings" (
    "id" uuid not null default gen_random_uuid(),
    "stripe_connection_id" uuid,
    "high_risk_threshold" numeric(5,2) default 70.00,
    "critical_risk_threshold" numeric(5,2) default 85.00,
    "auto_generate_emails" boolean default true,
    "auto_send_emails" boolean default false,
    "email_tone_preference" text default 'professional'::text,
    "notify_on_high_risk" boolean default true,
    "notify_on_critical_risk" boolean default true,
    "notification_email" text,
    "ai_enabled" boolean default true,
    "intervention_tracking_enabled" boolean default true,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now()
      );


alter table "public"."churn_prevention_settings" enable row level security;


  create table if not exists "public"."churn_training_data" (
    "id" uuid not null default gen_random_uuid(),
    "stripe_connection_id" uuid,
    "customer_id" text not null,
    "subscription_id" text not null,
    "features" jsonb not null,
    "churned" boolean not null,
    "churned_at" timestamp with time zone,
    "days_to_churn" integer,
    "observation_date" date not null,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."churn_training_data" enable row level security;


  create table if not exists "public"."cohorts" (
    "id" uuid not null default gen_random_uuid(),
    "stripe_connection_id" uuid,
    "cohort_month" date not null,
    "customers_count" integer default 0,
    "initial_mrr" numeric(10,2) default 0,
    "retention_data" jsonb default '{}'::jsonb,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now()
      );


alter table "public"."cohorts" enable row level security;


  create table if not exists "public"."customers_cache" (
    "id" uuid not null default gen_random_uuid(),
    "stripe_connection_id" uuid,
    "customer_id" text not null,
    "email" text,
    "name" text,
    "lifetime_value" numeric(10,2) default 0,
    "total_spent" numeric(10,2) default 0,
    "subscription_count" integer default 0,
    "created_at_stripe" timestamp with time zone,
    "first_subscription_date" timestamp with time zone,
    "last_subscription_date" timestamp with time zone,
    "synced_at" timestamp with time zone default now()
      );


alter table "public"."customers_cache" enable row level security;


  create table if not exists "public"."email_queue" (
    "id" uuid not null default gen_random_uuid(),
    "user_id" uuid,
    "to_email" text not null,
    "subject" text not null,
    "html_content" text not null,
    "text_content" text,
    "status" text default 'pending'::text,
    "sent_at" timestamp with time zone,
    "error_message" text,
    "metadata" jsonb,
    "created_at" timestamp with time zone default now()
      );



  create table if not exists "public"."feature_flags" (
    "id" uuid not null default gen_random_uuid(),
    "name" text not null,
    "description" text,
    "enabled" boolean default false,
    "rollout_percentage" integer default 0,
    "allowed_users" uuid[] default '{}'::uuid[],
    "allowed_plans" text[] default '{}'::text[],
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now()
      );



  create table if not exists "public"."invoices_cache" (
    "id" uuid not null default gen_random_uuid(),
    "stripe_connection_id" uuid,
    "invoice_id" text not null,
    "customer_id" text,
    "subscription_id" text,
    "status" text not null,
    "amount_due_cents" bigint default 0,
    "amount_paid_cents" bigint default 0,
    "attempt_count" integer default 0,
    "next_payment_attempt" timestamp with time zone,
    "hosted_invoice_url" text,
    "created_at_stripe" timestamp with time zone,
    "updated_at_stripe" timestamp with time zone,
    "synced_at" timestamp with time zone default now()
      );



  create table if not exists "public"."leak_action_assignments" (
    "id" uuid not null default gen_random_uuid(),
    "stripe_connection_id" uuid,
    "action_key" text not null,
    "leak_type" text not null,
    "assigned_to" uuid,
    "assigned_by" uuid,
    "status" text not null default 'open'::text,
    "updated_at" timestamp with time zone not null default now()
      );


alter table "public"."leak_action_assignments" enable row level security;


  create table if not exists "public"."leak_action_state" (
    "id" uuid not null default gen_random_uuid(),
    "user_id" uuid,
    "stripe_connection_id" uuid,
    "action_key" text not null,
    "leak_type" text not null,
    "is_done" boolean not null default false,
    "updated_at" timestamp with time zone not null default now()
      );


alter table "public"."leak_action_state" enable row level security;


  create table if not exists "public"."leak_email_log" (
    "id" uuid not null default gen_random_uuid(),
    "user_id" uuid,
    "stripe_connection_id" uuid,
    "sent_to" text,
    "subject" text,
    "provider_message_id" text,
    "created_at" timestamp with time zone not null default now()
      );



  create table if not exists "public"."leak_notifications" (
    "id" uuid not null default gen_random_uuid(),
    "user_id" uuid,
    "stripe_connection_id" uuid,
    "leak_id" uuid,
    "leak_type" text not null,
    "severity" text not null,
    "title" text not null,
    "message" text not null,
    "channel" text not null default 'in_app'::text,
    "provider_message_id" text,
    "created_at" timestamp with time zone not null default now(),
    "read_at" timestamp with time zone
      );


alter table "public"."leak_notifications" enable row level security;


  create table if not exists "public"."metrics_history" (
    "id" bigint generated by default as identity not null,
    "stripe_connection_id" uuid not null,
    "date" date not null default CURRENT_DATE,
    "mrr" numeric not null default 0,
    "active_subscriptions" integer not null default 0
      );


alter table "public"."metrics_history" enable row level security;


  create table if not exists "public"."referrals" (
    "id" uuid not null default gen_random_uuid(),
    "referrer_id" uuid,
    "referred_email" text,
    "referred_user_id" uuid,
    "status" text default 'pending'::text,
    "referral_code" text,
    "reward_amount" numeric(10,2),
    "reward_type" text,
    "expires_at" timestamp with time zone,
    "converted_at" timestamp with time zone,
    "created_at" timestamp with time zone default now()
      );



  create table if not exists "public"."revenue_recovery_events" (
    "id" uuid not null default gen_random_uuid(),
    "stripe_connection_id" uuid,
    "user_id" uuid,
    "invoice_id" text not null,
    "recovered_amount_cents" bigint not null default 0,
    "recovered_at" timestamp with time zone not null default now(),
    "meta" jsonb not null default '{}'::jsonb,
    "leak_type" text,
    "source_event_type" text,
    "leak_id" uuid
      );



  create table if not exists "public"."saved_searches" (
    "id" uuid not null default gen_random_uuid(),
    "user_id" uuid,
    "name" text not null,
    "query" jsonb not null,
    "is_default" boolean default false,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."saved_searches" enable row level security;


  create table if not exists "public"."stripe_connection_members" (
    "id" uuid not null default gen_random_uuid(),
    "stripe_connection_id" uuid,
    "user_id" uuid,
    "role" text not null default 'member'::text,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."stripe_connection_members" enable row level security;


  create table if not exists "public"."subscription_history" (
    "id" uuid not null default gen_random_uuid(),
    "user_id" uuid,
    "plan_from" text,
    "plan_to" text,
    "change_type" text,
    "stripe_event_id" text,
    "amount" numeric(10,2),
    "currency" text default 'USD'::text,
    "created_at" timestamp with time zone default now()
      );



  create table if not exists "public"."subscriptions_cache" (
    "id" uuid not null default gen_random_uuid(),
    "stripe_connection_id" uuid,
    "subscription_id" text not null,
    "customer_id" text not null,
    "status" text not null,
    "mrr_amount" numeric(10,2) default 0,
    "interval" text,
    "currency" text default 'USD'::text,
    "current_period_start" timestamp with time zone,
    "current_period_end" timestamp with time zone,
    "created_at_stripe" timestamp with time zone,
    "canceled_at" timestamp with time zone,
    "ended_at" timestamp with time zone,
    "plan_name" text,
    "price_id" text,
    "quantity" integer default 1,
    "synced_at" timestamp with time zone default now()
      );


alter table "public"."subscriptions_cache" enable row level security;


  create table if not exists "public"."sync_logs" (
    "id" uuid not null default gen_random_uuid(),
    "stripe_connection_id" uuid,
    "sync_type" text not null,
    "status" text not null,
    "subscriptions_synced" integer default 0,
    "customers_synced" integer default 0,
    "duration_ms" integer,
    "error_message" text,
    "error_details" jsonb,
    "created_at" timestamp with time zone default now()
      );



  create table if not exists "public"."team_members" (
    "id" uuid not null default gen_random_uuid(),
    "team_id" uuid,
    "user_id" uuid,
    "role" text default 'member'::text,
    "can_add_products" boolean default true,
    "can_delete_products" boolean default false,
    "can_manage_alerts" boolean default true,
    "can_view_analytics" boolean default true,
    "invited_by" uuid,
    "invited_at" timestamp with time zone,
    "joined_at" timestamp with time zone default now()
      );


alter table "public"."team_members" enable row level security;


  create table if not exists "public"."teams" (
    "id" uuid not null default gen_random_uuid(),
    "name" text not null,
    "owner_id" uuid,
    "plan" text default 'team'::text,
    "max_members" integer default 5,
    "max_products" integer default 1000,
    "stripe_customer_id" text,
    "stripe_subscription_id" text,
    "billing_email" text,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now()
      );


alter table "public"."teams" enable row level security;

alter table "public"."revenue_leaks" add column if not exists "created_at" timestamp with time zone default now();

CREATE UNIQUE INDEX IF NOT EXISTS analytics_events_pkey ON public.analytics_events USING btree (id);

CREATE UNIQUE INDEX IF NOT EXISTS api_usage_pkey ON public.api_usage USING btree (id);

CREATE UNIQUE INDEX IF NOT EXISTS churn_interventions_pkey ON public.churn_interventions USING btree (id);

CREATE UNIQUE INDEX IF NOT EXISTS churn_predictions_pkey ON public.churn_predictions USING btree (id);

CREATE UNIQUE INDEX IF NOT EXISTS churn_predictions_stripe_connection_id_customer_id_subscrip_key ON public.churn_predictions USING btree (stripe_connection_id, customer_id, subscription_id, created_at);

CREATE UNIQUE INDEX IF NOT EXISTS churn_prevention_settings_pkey ON public.churn_prevention_settings USING btree (id);

CREATE UNIQUE INDEX IF NOT EXISTS churn_prevention_settings_stripe_connection_id_key ON public.churn_prevention_settings USING btree (stripe_connection_id);

CREATE UNIQUE INDEX IF NOT EXISTS churn_training_data_pkey ON public.churn_training_data USING btree (id);

CREATE UNIQUE INDEX IF NOT EXISTS cohorts_pkey ON public.cohorts USING btree (id);

CREATE UNIQUE INDEX IF NOT EXISTS cohorts_stripe_connection_id_cohort_month_key ON public.cohorts USING btree (stripe_connection_id, cohort_month);

CREATE UNIQUE INDEX IF NOT EXISTS customers_cache_pkey ON public.customers_cache USING btree (id);

CREATE UNIQUE INDEX IF NOT EXISTS customers_cache_stripe_connection_id_customer_id_key ON public.customers_cache USING btree (stripe_connection_id, customer_id);

CREATE UNIQUE INDEX IF NOT EXISTS email_queue_pkey ON public.email_queue USING btree (id);

CREATE UNIQUE INDEX IF NOT EXISTS feature_flags_name_key ON public.feature_flags USING btree (name);

CREATE UNIQUE INDEX IF NOT EXISTS feature_flags_pkey ON public.feature_flags USING btree (id);

CREATE INDEX IF NOT EXISTS idx_analytics_events_name ON public.analytics_events USING btree (event_name);

CREATE INDEX IF NOT EXISTS idx_analytics_events_user_created ON public.analytics_events USING btree (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_api_usage_user_created ON public.api_usage USING btree (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_churn_interventions_connection ON public.churn_interventions USING btree (stripe_connection_id);

CREATE INDEX IF NOT EXISTS idx_churn_interventions_prediction ON public.churn_interventions USING btree (churn_prediction_id);

CREATE INDEX IF NOT EXISTS idx_churn_predictions_connection ON public.churn_predictions USING btree (stripe_connection_id);

CREATE INDEX IF NOT EXISTS idx_churn_predictions_customer ON public.churn_predictions USING btree (customer_id);

CREATE INDEX IF NOT EXISTS idx_churn_predictions_date ON public.churn_predictions USING btree (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_churn_predictions_risk ON public.churn_predictions USING btree (stripe_connection_id, risk_level, status);

CREATE INDEX IF NOT EXISTS idx_churn_training_data_connection ON public.churn_training_data USING btree (stripe_connection_id);

CREATE INDEX IF NOT EXISTS idx_cohorts_connection_month ON public.cohorts USING btree (stripe_connection_id, cohort_month DESC);

CREATE INDEX IF NOT EXISTS idx_customers_cache_connection ON public.customers_cache USING btree (stripe_connection_id);

CREATE INDEX IF NOT EXISTS idx_email_queue_status ON public.email_queue USING btree (status, created_at);

CREATE INDEX IF NOT EXISTS idx_subscription_history_user ON public.subscription_history USING btree (user_id);

CREATE INDEX IF NOT EXISTS idx_subscriptions_cache_connection ON public.subscriptions_cache USING btree (stripe_connection_id);

CREATE INDEX IF NOT EXISTS idx_team_members_team ON public.team_members USING btree (team_id);

CREATE INDEX IF NOT EXISTS idx_team_members_user ON public.team_members USING btree (user_id);

CREATE INDEX IF NOT EXISTS invoices_cache_conn_idx ON public.invoices_cache USING btree (stripe_connection_id);

CREATE INDEX IF NOT EXISTS invoices_cache_created_idx ON public.invoices_cache USING btree (created_at_stripe);

CREATE UNIQUE INDEX IF NOT EXISTS invoices_cache_pkey ON public.invoices_cache USING btree (id);

CREATE INDEX IF NOT EXISTS invoices_cache_status_idx ON public.invoices_cache USING btree (status);

CREATE UNIQUE INDEX IF NOT EXISTS invoices_cache_stripe_connection_id_invoice_id_key ON public.invoices_cache USING btree (stripe_connection_id, invoice_id);

CREATE INDEX IF NOT EXISTS leak_action_assignments_assigned_to_idx ON public.leak_action_assignments USING btree (assigned_to);

CREATE INDEX IF NOT EXISTS leak_action_assignments_conn_idx ON public.leak_action_assignments USING btree (stripe_connection_id);

CREATE UNIQUE INDEX IF NOT EXISTS leak_action_assignments_pkey ON public.leak_action_assignments USING btree (id);

CREATE UNIQUE INDEX IF NOT EXISTS leak_action_assignments_stripe_connection_id_action_key_key ON public.leak_action_assignments USING btree (stripe_connection_id, action_key);

CREATE INDEX IF NOT EXISTS leak_action_state_conn_idx ON public.leak_action_state USING btree (stripe_connection_id);

CREATE UNIQUE INDEX IF NOT EXISTS leak_action_state_pkey ON public.leak_action_state USING btree (id);

CREATE UNIQUE INDEX IF NOT EXISTS leak_action_state_user_id_stripe_connection_id_action_key_key ON public.leak_action_state USING btree (user_id, stripe_connection_id, action_key);

CREATE INDEX IF NOT EXISTS leak_action_state_user_idx ON public.leak_action_state USING btree (user_id);

CREATE INDEX IF NOT EXISTS leak_email_log_created_idx ON public.leak_email_log USING btree (created_at);

CREATE UNIQUE INDEX IF NOT EXISTS leak_email_log_pkey ON public.leak_email_log USING btree (id);

CREATE INDEX IF NOT EXISTS leak_email_log_user_idx ON public.leak_email_log USING btree (user_id);

CREATE INDEX IF NOT EXISTS leak_notifications_channel_idx ON public.leak_notifications USING btree (channel);

CREATE INDEX IF NOT EXISTS leak_notifications_created_idx ON public.leak_notifications USING btree (created_at);

CREATE UNIQUE INDEX IF NOT EXISTS leak_notifications_dedupe_idx ON public.leak_notifications USING btree (leak_id, channel);

CREATE UNIQUE INDEX IF NOT EXISTS leak_notifications_pkey ON public.leak_notifications USING btree (id);

CREATE INDEX IF NOT EXISTS leak_notifications_read_idx ON public.leak_notifications USING btree (read_at);

CREATE INDEX IF NOT EXISTS leak_notifications_user_idx ON public.leak_notifications USING btree (user_id);

CREATE UNIQUE INDEX IF NOT EXISTS metrics_history_pkey ON public.metrics_history USING btree (id);

CREATE UNIQUE INDEX IF NOT EXISTS metrics_history_stripe_connection_id_date_key ON public.metrics_history USING btree (stripe_connection_id, date);

CREATE UNIQUE INDEX IF NOT EXISTS referrals_pkey ON public.referrals USING btree (id);

CREATE UNIQUE INDEX IF NOT EXISTS referrals_referral_code_key ON public.referrals USING btree (referral_code);

CREATE INDEX IF NOT EXISTS revenue_recovery_events_conn_idx ON public.revenue_recovery_events USING btree (stripe_connection_id);

CREATE INDEX IF NOT EXISTS revenue_recovery_events_leak_id_idx ON public.revenue_recovery_events USING btree (leak_id);

CREATE INDEX IF NOT EXISTS revenue_recovery_events_leak_type_idx ON public.revenue_recovery_events USING btree (leak_type);

CREATE UNIQUE INDEX IF NOT EXISTS revenue_recovery_events_pkey ON public.revenue_recovery_events USING btree (id);

CREATE INDEX IF NOT EXISTS revenue_recovery_events_recovered_at_idx ON public.revenue_recovery_events USING btree (recovered_at);

CREATE UNIQUE INDEX IF NOT EXISTS revenue_recovery_events_stripe_connection_id_invoice_id_rec_key ON public.revenue_recovery_events USING btree (stripe_connection_id, invoice_id, recovered_at);

CREATE INDEX IF NOT EXISTS revenue_recovery_events_user_idx ON public.revenue_recovery_events USING btree (user_id);

CREATE UNIQUE INDEX IF NOT EXISTS saved_searches_pkey ON public.saved_searches USING btree (id);

CREATE INDEX IF NOT EXISTS stripe_connection_members_conn_idx ON public.stripe_connection_members USING btree (stripe_connection_id);

CREATE UNIQUE INDEX IF NOT EXISTS stripe_connection_members_pkey ON public.stripe_connection_members USING btree (id);

CREATE UNIQUE INDEX IF NOT EXISTS stripe_connection_members_stripe_connection_id_user_id_key ON public.stripe_connection_members USING btree (stripe_connection_id, user_id);

CREATE INDEX IF NOT EXISTS stripe_connection_members_user_idx ON public.stripe_connection_members USING btree (user_id);

CREATE UNIQUE INDEX IF NOT EXISTS subscription_history_pkey ON public.subscription_history USING btree (id);

CREATE UNIQUE INDEX IF NOT EXISTS subscriptions_cache_pkey ON public.subscriptions_cache USING btree (id);

CREATE UNIQUE INDEX IF NOT EXISTS subscriptions_cache_stripe_connection_id_subscription_id_key ON public.subscriptions_cache USING btree (stripe_connection_id, subscription_id);

CREATE UNIQUE INDEX IF NOT EXISTS sync_logs_pkey ON public.sync_logs USING btree (id);

CREATE UNIQUE INDEX IF NOT EXISTS team_members_pkey ON public.team_members USING btree (id);

CREATE UNIQUE INDEX IF NOT EXISTS team_members_team_id_user_id_key ON public.team_members USING btree (team_id, user_id);

CREATE UNIQUE INDEX IF NOT EXISTS teams_pkey ON public.teams USING btree (id);

CREATE UNIQUE INDEX IF NOT EXISTS teams_stripe_customer_id_key ON public.teams USING btree (stripe_customer_id);

alter table "public"."analytics_events" add constraint "analytics_events_pkey" PRIMARY KEY using index "analytics_events_pkey";

alter table "public"."api_usage" add constraint "api_usage_pkey" PRIMARY KEY using index "api_usage_pkey";

alter table "public"."churn_interventions" add constraint "churn_interventions_pkey" PRIMARY KEY using index "churn_interventions_pkey";

alter table "public"."churn_predictions" add constraint "churn_predictions_pkey" PRIMARY KEY using index "churn_predictions_pkey";

alter table "public"."churn_prevention_settings" add constraint "churn_prevention_settings_pkey" PRIMARY KEY using index "churn_prevention_settings_pkey";

alter table "public"."churn_training_data" add constraint "churn_training_data_pkey" PRIMARY KEY using index "churn_training_data_pkey";

alter table "public"."cohorts" add constraint "cohorts_pkey" PRIMARY KEY using index "cohorts_pkey";

alter table "public"."customers_cache" add constraint "customers_cache_pkey" PRIMARY KEY using index "customers_cache_pkey";

alter table "public"."email_queue" add constraint "email_queue_pkey" PRIMARY KEY using index "email_queue_pkey";

alter table "public"."feature_flags" add constraint "feature_flags_pkey" PRIMARY KEY using index "feature_flags_pkey";

alter table "public"."invoices_cache" add constraint "invoices_cache_pkey" PRIMARY KEY using index "invoices_cache_pkey";

alter table "public"."leak_action_assignments" add constraint "leak_action_assignments_pkey" PRIMARY KEY using index "leak_action_assignments_pkey";

alter table "public"."leak_action_state" add constraint "leak_action_state_pkey" PRIMARY KEY using index "leak_action_state_pkey";

alter table "public"."leak_email_log" add constraint "leak_email_log_pkey" PRIMARY KEY using index "leak_email_log_pkey";

alter table "public"."leak_notifications" add constraint "leak_notifications_pkey" PRIMARY KEY using index "leak_notifications_pkey";

alter table "public"."metrics_history" add constraint "metrics_history_pkey" PRIMARY KEY using index "metrics_history_pkey";

alter table "public"."referrals" add constraint "referrals_pkey" PRIMARY KEY using index "referrals_pkey";

alter table "public"."revenue_recovery_events" add constraint "revenue_recovery_events_pkey" PRIMARY KEY using index "revenue_recovery_events_pkey";

alter table "public"."saved_searches" add constraint "saved_searches_pkey" PRIMARY KEY using index "saved_searches_pkey";

alter table "public"."stripe_connection_members" add constraint "stripe_connection_members_pkey" PRIMARY KEY using index "stripe_connection_members_pkey";

alter table "public"."subscription_history" add constraint "subscription_history_pkey" PRIMARY KEY using index "subscription_history_pkey";

alter table "public"."subscriptions_cache" add constraint "subscriptions_cache_pkey" PRIMARY KEY using index "subscriptions_cache_pkey";

alter table "public"."sync_logs" add constraint "sync_logs_pkey" PRIMARY KEY using index "sync_logs_pkey";

alter table "public"."team_members" add constraint "team_members_pkey" PRIMARY KEY using index "team_members_pkey";

alter table "public"."teams" add constraint "teams_pkey" PRIMARY KEY using index "teams_pkey";

alter table "public"."churn_interventions" add constraint "churn_interventions_actioned_by_fkey" FOREIGN KEY (actioned_by) REFERENCES auth.users(id) not valid;

alter table "public"."churn_interventions" validate constraint "churn_interventions_actioned_by_fkey";

alter table "public"."churn_interventions" add constraint "churn_interventions_churn_prediction_id_fkey" FOREIGN KEY (churn_prediction_id) REFERENCES public.churn_predictions(id) ON DELETE CASCADE not valid;

alter table "public"."churn_interventions" validate constraint "churn_interventions_churn_prediction_id_fkey";

alter table "public"."churn_predictions" add constraint "churn_predictions_actioned_by_fkey" FOREIGN KEY (actioned_by) REFERENCES auth.users(id) not valid;

alter table "public"."churn_predictions" validate constraint "churn_predictions_actioned_by_fkey";

alter table "public"."churn_predictions" add constraint "churn_predictions_risk_level_check" CHECK ((risk_level = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'critical'::text]))) not valid;

alter table "public"."churn_predictions" validate constraint "churn_predictions_risk_level_check";

alter table "public"."churn_predictions" add constraint "churn_predictions_status_check" CHECK ((status = ANY (ARRAY['pending'::text, 'reviewed'::text, 'actioned'::text, 'resolved'::text, 'churned'::text]))) not valid;

alter table "public"."churn_predictions" validate constraint "churn_predictions_status_check";

alter table "public"."churn_predictions" add constraint "churn_predictions_stripe_connection_id_customer_id_subscrip_key" UNIQUE using index "churn_predictions_stripe_connection_id_customer_id_subscrip_key";

alter table "public"."churn_prevention_settings" add constraint "churn_prevention_settings_stripe_connection_id_key" UNIQUE using index "churn_prevention_settings_stripe_connection_id_key";

alter table "public"."cohorts" add constraint "cohorts_stripe_connection_id_cohort_month_key" UNIQUE using index "cohorts_stripe_connection_id_cohort_month_key";

alter table "public"."customers_cache" add constraint "customers_cache_stripe_connection_id_customer_id_key" UNIQUE using index "customers_cache_stripe_connection_id_customer_id_key";

alter table "public"."email_queue" add constraint "email_queue_status_check" CHECK ((status = ANY (ARRAY['pending'::text, 'sent'::text, 'failed'::text, 'bounced'::text]))) not valid;

alter table "public"."email_queue" validate constraint "email_queue_status_check";

alter table "public"."feature_flags" add constraint "feature_flags_name_key" UNIQUE using index "feature_flags_name_key";

alter table "public"."feature_flags" add constraint "feature_flags_rollout_percentage_check" CHECK (((rollout_percentage >= 0) AND (rollout_percentage <= 100))) not valid;

alter table "public"."feature_flags" validate constraint "feature_flags_rollout_percentage_check";

alter table "public"."invoices_cache" add constraint "invoices_cache_stripe_connection_id_invoice_id_key" UNIQUE using index "invoices_cache_stripe_connection_id_invoice_id_key";

alter table "public"."leak_action_assignments" add constraint "leak_action_assignments_assigned_by_fkey" FOREIGN KEY (assigned_by) REFERENCES auth.users(id) ON DELETE SET NULL not valid;

alter table "public"."leak_action_assignments" validate constraint "leak_action_assignments_assigned_by_fkey";

alter table "public"."leak_action_assignments" add constraint "leak_action_assignments_assigned_to_fkey" FOREIGN KEY (assigned_to) REFERENCES auth.users(id) ON DELETE SET NULL not valid;

alter table "public"."leak_action_assignments" validate constraint "leak_action_assignments_assigned_to_fkey";

alter table "public"."leak_action_assignments" add constraint "leak_action_assignments_stripe_connection_id_action_key_key" UNIQUE using index "leak_action_assignments_stripe_connection_id_action_key_key";

alter table "public"."leak_action_state" add constraint "leak_action_state_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."leak_action_state" validate constraint "leak_action_state_user_id_fkey";

alter table "public"."leak_action_state" add constraint "leak_action_state_user_id_stripe_connection_id_action_key_key" UNIQUE using index "leak_action_state_user_id_stripe_connection_id_action_key_key";

alter table "public"."leak_email_log" add constraint "leak_email_log_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."leak_email_log" validate constraint "leak_email_log_user_id_fkey";

alter table "public"."leak_notifications" add constraint "leak_notifications_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."leak_notifications" validate constraint "leak_notifications_user_id_fkey";

alter table "public"."metrics_history" add constraint "metrics_history_stripe_connection_id_date_key" UNIQUE using index "metrics_history_stripe_connection_id_date_key";

alter table "public"."referrals" add constraint "referrals_referral_code_key" UNIQUE using index "referrals_referral_code_key";

alter table "public"."referrals" add constraint "referrals_reward_type_check" CHECK ((reward_type = ANY (ARRAY['credit'::text, 'discount'::text, 'free_month'::text]))) not valid;

alter table "public"."referrals" validate constraint "referrals_reward_type_check";

alter table "public"."referrals" add constraint "referrals_status_check" CHECK ((status = ANY (ARRAY['pending'::text, 'signed_up'::text, 'converted'::text, 'expired'::text]))) not valid;

alter table "public"."referrals" validate constraint "referrals_status_check";

alter table "public"."revenue_recovery_events" add constraint "revenue_recovery_events_stripe_connection_id_invoice_id_rec_key" UNIQUE using index "revenue_recovery_events_stripe_connection_id_invoice_id_rec_key";

alter table "public"."revenue_recovery_events" add constraint "revenue_recovery_events_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."revenue_recovery_events" validate constraint "revenue_recovery_events_user_id_fkey";

alter table "public"."stripe_connection_members" add constraint "stripe_connection_members_stripe_connection_id_user_id_key" UNIQUE using index "stripe_connection_members_stripe_connection_id_user_id_key";

alter table "public"."stripe_connection_members" add constraint "stripe_connection_members_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."stripe_connection_members" validate constraint "stripe_connection_members_user_id_fkey";

alter table "public"."subscription_history" add constraint "subscription_history_change_type_check" CHECK ((change_type = ANY (ARRAY['upgrade'::text, 'downgrade'::text, 'cancel'::text, 'resume'::text]))) not valid;

alter table "public"."subscription_history" validate constraint "subscription_history_change_type_check";

alter table "public"."subscriptions_cache" add constraint "subscriptions_cache_stripe_connection_id_subscription_id_key" UNIQUE using index "subscriptions_cache_stripe_connection_id_subscription_id_key";

alter table "public"."team_members" add constraint "team_members_role_check" CHECK ((role = ANY (ARRAY['owner'::text, 'admin'::text, 'member'::text]))) not valid;

alter table "public"."team_members" validate constraint "team_members_role_check";

alter table "public"."team_members" add constraint "team_members_team_id_fkey" FOREIGN KEY (team_id) REFERENCES public.teams(id) ON DELETE CASCADE not valid;

alter table "public"."team_members" validate constraint "team_members_team_id_fkey";

alter table "public"."team_members" add constraint "team_members_team_id_user_id_key" UNIQUE using index "team_members_team_id_user_id_key";

alter table "public"."teams" add constraint "teams_plan_check" CHECK ((plan = ANY (ARRAY['team'::text, 'enterprise'::text]))) not valid;

alter table "public"."teams" validate constraint "teams_plan_check";

alter table "public"."teams" add constraint "teams_stripe_customer_id_key" UNIQUE using index "teams_stripe_customer_id_key";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.check_plan_limits(p_user_id uuid, p_resource text)
 RETURNS boolean
 LANGUAGE plpgsql
AS $function$
DECLARE
  v_plan TEXT;
  v_tracked_count INTEGER;
  v_limit INTEGER;
BEGIN
  SELECT plan, tracked_count INTO v_plan, v_tracked_count
  FROM user_profiles
  WHERE id = p_user_id;

  IF p_resource = 'products' THEN
    CASE v_plan
      WHEN 'free' THEN v_limit := 5;
      WHEN 'pro' THEN v_limit := 999;
      WHEN 'ultra' THEN v_limit := 999;
      WHEN 'mega' THEN v_limit := 999;
      ELSE v_limit := 5;
    END CASE;
    
    RETURN v_tracked_count < v_limit;
  END IF;

  RETURN true;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.check_scenario_limit(p_user_id uuid)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_tier TEXT;
  v_limit INTEGER;
  v_used INTEGER;
BEGIN
  SELECT subscription_tier, monthly_scenario_limit, scenarios_used_this_month
  INTO v_tier, v_limit, v_used
  FROM user_profiles
  WHERE user_id = p_user_id;
  IF v_tier = 'starter' THEN
    RETURN FALSE;
  ELSIF v_tier = 'pro' THEN
    RETURN COALESCE(v_used, 0) < COALESCE(v_limit, 3);
  ELSIF v_tier = 'business' THEN
    RETURN TRUE;
  ELSE
    RETURN FALSE;
  END IF;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_user_tier(p_user_id uuid)
 RETURNS text
 LANGUAGE sql
 SECURITY DEFINER
AS $function$
  SELECT subscription_tier 
  FROM user_profiles 
  WHERE user_id = p_user_id;
$function$
;

CREATE OR REPLACE FUNCTION public.has_feature_access(p_user_id uuid, p_feature text)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_tier TEXT;
BEGIN
  SELECT subscription_tier INTO v_tier
  FROM user_profiles
  WHERE user_id = p_user_id;
  IF v_tier = 'starter' THEN
    RETURN p_feature IN ('dashboard', 'metrics', 'stripe_connection');
  ELSIF v_tier = 'pro' THEN
    RETURN p_feature IN (
      'dashboard', 'metrics', 'stripe_connection',
      'churn_prevention', 'peer_benchmarking', 'scenarios_limited'
    );
  ELSIF v_tier = 'business' THEN
    RETURN TRUE;
  ELSE
    RETURN FALSE;
  END IF;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.increment_scenario_usage(p_user_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  UPDATE user_profiles
  SET scenarios_used_this_month = COALESCE(scenarios_used_this_month, 0) + 1
  WHERE user_id = p_user_id;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.reset_monthly_scenario_usage()
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  UPDATE user_profiles
  SET scenarios_used_this_month = 0
  WHERE subscription_tier = 'pro';
END;
$function$
;

CREATE OR REPLACE FUNCTION public.reset_monthly_usage()
 RETURNS void
 LANGUAGE plpgsql
AS $function$
BEGIN
  UPDATE user_profiles
  SET api_calls_this_month = 0
  WHERE EXTRACT(DAY FROM NOW()) = 1; -- Reset on the 1st of each month
END;
$function$
;

CREATE OR REPLACE FUNCTION public.set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.track_api_usage(p_user_id uuid, p_endpoint text, p_method text, p_status_code integer, p_response_time_ms integer)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
BEGIN
  -- Insert usage record
  INSERT INTO api_usage (
    user_id, endpoint, method, status_code, response_time_ms
  ) VALUES (
    p_user_id, p_endpoint, p_method, p_status_code, p_response_time_ms
  );

  -- Update monthly counter
  UPDATE user_profiles
  SET 
    api_calls_this_month = api_calls_this_month + 1,
    last_api_call = NOW()
  WHERE id = p_user_id;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_churn_prediction_timestamp()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_updated_at_saas()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.updated_at = TIMEZONE('utc', NOW());
  RETURN NEW;
END;
$function$
;

create or replace view "public"."view_connection_metrics" as  SELECT stripe_connection_id,
    count(DISTINCT customer_id) AS total_customers,
    count(*) FILTER (WHERE (status = ANY (ARRAY['active'::text, 'trialing'::text]))) AS active_subscriptions,
    COALESCE(sum(mrr_amount) FILTER (WHERE (status = ANY (ARRAY['active'::text, 'trialing'::text]))), (0)::numeric) AS mrr
   FROM public.subscriptions_cache
  GROUP BY stripe_connection_id;


grant delete on table "public"."analytics_events" to "anon";

grant insert on table "public"."analytics_events" to "anon";

grant references on table "public"."analytics_events" to "anon";

grant select on table "public"."analytics_events" to "anon";

grant trigger on table "public"."analytics_events" to "anon";

grant truncate on table "public"."analytics_events" to "anon";

grant update on table "public"."analytics_events" to "anon";

grant delete on table "public"."analytics_events" to "authenticated";

grant insert on table "public"."analytics_events" to "authenticated";

grant references on table "public"."analytics_events" to "authenticated";

grant select on table "public"."analytics_events" to "authenticated";

grant trigger on table "public"."analytics_events" to "authenticated";

grant truncate on table "public"."analytics_events" to "authenticated";

grant update on table "public"."analytics_events" to "authenticated";

grant delete on table "public"."analytics_events" to "service_role";

grant insert on table "public"."analytics_events" to "service_role";

grant references on table "public"."analytics_events" to "service_role";

grant select on table "public"."analytics_events" to "service_role";

grant trigger on table "public"."analytics_events" to "service_role";

grant truncate on table "public"."analytics_events" to "service_role";

grant update on table "public"."analytics_events" to "service_role";

grant delete on table "public"."api_usage" to "anon";

grant insert on table "public"."api_usage" to "anon";

grant references on table "public"."api_usage" to "anon";

grant select on table "public"."api_usage" to "anon";

grant trigger on table "public"."api_usage" to "anon";

grant truncate on table "public"."api_usage" to "anon";

grant update on table "public"."api_usage" to "anon";

grant delete on table "public"."api_usage" to "authenticated";

grant insert on table "public"."api_usage" to "authenticated";

grant references on table "public"."api_usage" to "authenticated";

grant select on table "public"."api_usage" to "authenticated";

grant trigger on table "public"."api_usage" to "authenticated";

grant truncate on table "public"."api_usage" to "authenticated";

grant update on table "public"."api_usage" to "authenticated";

grant delete on table "public"."api_usage" to "service_role";

grant insert on table "public"."api_usage" to "service_role";

grant references on table "public"."api_usage" to "service_role";

grant select on table "public"."api_usage" to "service_role";

grant trigger on table "public"."api_usage" to "service_role";

grant truncate on table "public"."api_usage" to "service_role";

grant update on table "public"."api_usage" to "service_role";

grant delete on table "public"."churn_interventions" to "anon";

grant insert on table "public"."churn_interventions" to "anon";

grant references on table "public"."churn_interventions" to "anon";

grant select on table "public"."churn_interventions" to "anon";

grant trigger on table "public"."churn_interventions" to "anon";

grant truncate on table "public"."churn_interventions" to "anon";

grant update on table "public"."churn_interventions" to "anon";

grant delete on table "public"."churn_interventions" to "authenticated";

grant insert on table "public"."churn_interventions" to "authenticated";

grant references on table "public"."churn_interventions" to "authenticated";

grant select on table "public"."churn_interventions" to "authenticated";

grant trigger on table "public"."churn_interventions" to "authenticated";

grant truncate on table "public"."churn_interventions" to "authenticated";

grant update on table "public"."churn_interventions" to "authenticated";

grant delete on table "public"."churn_interventions" to "service_role";

grant insert on table "public"."churn_interventions" to "service_role";

grant references on table "public"."churn_interventions" to "service_role";

grant select on table "public"."churn_interventions" to "service_role";

grant trigger on table "public"."churn_interventions" to "service_role";

grant truncate on table "public"."churn_interventions" to "service_role";

grant update on table "public"."churn_interventions" to "service_role";

grant delete on table "public"."churn_predictions" to "anon";

grant insert on table "public"."churn_predictions" to "anon";

grant references on table "public"."churn_predictions" to "anon";

grant select on table "public"."churn_predictions" to "anon";

grant trigger on table "public"."churn_predictions" to "anon";

grant truncate on table "public"."churn_predictions" to "anon";

grant update on table "public"."churn_predictions" to "anon";

grant delete on table "public"."churn_predictions" to "authenticated";

grant insert on table "public"."churn_predictions" to "authenticated";

grant references on table "public"."churn_predictions" to "authenticated";

grant select on table "public"."churn_predictions" to "authenticated";

grant trigger on table "public"."churn_predictions" to "authenticated";

grant truncate on table "public"."churn_predictions" to "authenticated";

grant update on table "public"."churn_predictions" to "authenticated";

grant delete on table "public"."churn_predictions" to "service_role";

grant insert on table "public"."churn_predictions" to "service_role";

grant references on table "public"."churn_predictions" to "service_role";

grant select on table "public"."churn_predictions" to "service_role";

grant trigger on table "public"."churn_predictions" to "service_role";

grant truncate on table "public"."churn_predictions" to "service_role";

grant update on table "public"."churn_predictions" to "service_role";

grant delete on table "public"."churn_prevention_settings" to "anon";

grant insert on table "public"."churn_prevention_settings" to "anon";

grant references on table "public"."churn_prevention_settings" to "anon";

grant select on table "public"."churn_prevention_settings" to "anon";

grant trigger on table "public"."churn_prevention_settings" to "anon";

grant truncate on table "public"."churn_prevention_settings" to "anon";

grant update on table "public"."churn_prevention_settings" to "anon";

grant delete on table "public"."churn_prevention_settings" to "authenticated";

grant insert on table "public"."churn_prevention_settings" to "authenticated";

grant references on table "public"."churn_prevention_settings" to "authenticated";

grant select on table "public"."churn_prevention_settings" to "authenticated";

grant trigger on table "public"."churn_prevention_settings" to "authenticated";

grant truncate on table "public"."churn_prevention_settings" to "authenticated";

grant update on table "public"."churn_prevention_settings" to "authenticated";

grant delete on table "public"."churn_prevention_settings" to "service_role";

grant insert on table "public"."churn_prevention_settings" to "service_role";

grant references on table "public"."churn_prevention_settings" to "service_role";

grant select on table "public"."churn_prevention_settings" to "service_role";

grant trigger on table "public"."churn_prevention_settings" to "service_role";

grant truncate on table "public"."churn_prevention_settings" to "service_role";

grant update on table "public"."churn_prevention_settings" to "service_role";

grant delete on table "public"."churn_training_data" to "anon";

grant insert on table "public"."churn_training_data" to "anon";

grant references on table "public"."churn_training_data" to "anon";

grant select on table "public"."churn_training_data" to "anon";

grant trigger on table "public"."churn_training_data" to "anon";

grant truncate on table "public"."churn_training_data" to "anon";

grant update on table "public"."churn_training_data" to "anon";

grant delete on table "public"."churn_training_data" to "authenticated";

grant insert on table "public"."churn_training_data" to "authenticated";

grant references on table "public"."churn_training_data" to "authenticated";

grant select on table "public"."churn_training_data" to "authenticated";

grant trigger on table "public"."churn_training_data" to "authenticated";

grant truncate on table "public"."churn_training_data" to "authenticated";

grant update on table "public"."churn_training_data" to "authenticated";

grant delete on table "public"."churn_training_data" to "service_role";

grant insert on table "public"."churn_training_data" to "service_role";

grant references on table "public"."churn_training_data" to "service_role";

grant select on table "public"."churn_training_data" to "service_role";

grant trigger on table "public"."churn_training_data" to "service_role";

grant truncate on table "public"."churn_training_data" to "service_role";

grant update on table "public"."churn_training_data" to "service_role";

grant delete on table "public"."cohorts" to "anon";

grant insert on table "public"."cohorts" to "anon";

grant references on table "public"."cohorts" to "anon";

grant select on table "public"."cohorts" to "anon";

grant trigger on table "public"."cohorts" to "anon";

grant truncate on table "public"."cohorts" to "anon";

grant update on table "public"."cohorts" to "anon";

grant delete on table "public"."cohorts" to "authenticated";

grant insert on table "public"."cohorts" to "authenticated";

grant references on table "public"."cohorts" to "authenticated";

grant select on table "public"."cohorts" to "authenticated";

grant trigger on table "public"."cohorts" to "authenticated";

grant truncate on table "public"."cohorts" to "authenticated";

grant update on table "public"."cohorts" to "authenticated";

grant delete on table "public"."cohorts" to "service_role";

grant insert on table "public"."cohorts" to "service_role";

grant references on table "public"."cohorts" to "service_role";

grant select on table "public"."cohorts" to "service_role";

grant trigger on table "public"."cohorts" to "service_role";

grant truncate on table "public"."cohorts" to "service_role";

grant update on table "public"."cohorts" to "service_role";

grant delete on table "public"."customers_cache" to "anon";

grant insert on table "public"."customers_cache" to "anon";

grant references on table "public"."customers_cache" to "anon";

grant select on table "public"."customers_cache" to "anon";

grant trigger on table "public"."customers_cache" to "anon";

grant truncate on table "public"."customers_cache" to "anon";

grant update on table "public"."customers_cache" to "anon";

grant delete on table "public"."customers_cache" to "authenticated";

grant insert on table "public"."customers_cache" to "authenticated";

grant references on table "public"."customers_cache" to "authenticated";

grant select on table "public"."customers_cache" to "authenticated";

grant trigger on table "public"."customers_cache" to "authenticated";

grant truncate on table "public"."customers_cache" to "authenticated";

grant update on table "public"."customers_cache" to "authenticated";

grant delete on table "public"."customers_cache" to "service_role";

grant insert on table "public"."customers_cache" to "service_role";

grant references on table "public"."customers_cache" to "service_role";

grant select on table "public"."customers_cache" to "service_role";

grant trigger on table "public"."customers_cache" to "service_role";

grant truncate on table "public"."customers_cache" to "service_role";

grant update on table "public"."customers_cache" to "service_role";

grant delete on table "public"."email_queue" to "anon";

grant insert on table "public"."email_queue" to "anon";

grant references on table "public"."email_queue" to "anon";

grant select on table "public"."email_queue" to "anon";

grant trigger on table "public"."email_queue" to "anon";

grant truncate on table "public"."email_queue" to "anon";

grant update on table "public"."email_queue" to "anon";

grant delete on table "public"."email_queue" to "authenticated";

grant insert on table "public"."email_queue" to "authenticated";

grant references on table "public"."email_queue" to "authenticated";

grant select on table "public"."email_queue" to "authenticated";

grant trigger on table "public"."email_queue" to "authenticated";

grant truncate on table "public"."email_queue" to "authenticated";

grant update on table "public"."email_queue" to "authenticated";

grant delete on table "public"."email_queue" to "service_role";

grant insert on table "public"."email_queue" to "service_role";

grant references on table "public"."email_queue" to "service_role";

grant select on table "public"."email_queue" to "service_role";

grant trigger on table "public"."email_queue" to "service_role";

grant truncate on table "public"."email_queue" to "service_role";

grant update on table "public"."email_queue" to "service_role";

grant delete on table "public"."feature_flags" to "anon";

grant insert on table "public"."feature_flags" to "anon";

grant references on table "public"."feature_flags" to "anon";

grant select on table "public"."feature_flags" to "anon";

grant trigger on table "public"."feature_flags" to "anon";

grant truncate on table "public"."feature_flags" to "anon";

grant update on table "public"."feature_flags" to "anon";

grant delete on table "public"."feature_flags" to "authenticated";

grant insert on table "public"."feature_flags" to "authenticated";

grant references on table "public"."feature_flags" to "authenticated";

grant select on table "public"."feature_flags" to "authenticated";

grant trigger on table "public"."feature_flags" to "authenticated";

grant truncate on table "public"."feature_flags" to "authenticated";

grant update on table "public"."feature_flags" to "authenticated";

grant delete on table "public"."feature_flags" to "service_role";

grant insert on table "public"."feature_flags" to "service_role";

grant references on table "public"."feature_flags" to "service_role";

grant select on table "public"."feature_flags" to "service_role";

grant trigger on table "public"."feature_flags" to "service_role";

grant truncate on table "public"."feature_flags" to "service_role";

grant update on table "public"."feature_flags" to "service_role";

grant delete on table "public"."invoices_cache" to "anon";

grant insert on table "public"."invoices_cache" to "anon";

grant references on table "public"."invoices_cache" to "anon";

grant select on table "public"."invoices_cache" to "anon";

grant trigger on table "public"."invoices_cache" to "anon";

grant truncate on table "public"."invoices_cache" to "anon";

grant update on table "public"."invoices_cache" to "anon";

grant delete on table "public"."invoices_cache" to "authenticated";

grant insert on table "public"."invoices_cache" to "authenticated";

grant references on table "public"."invoices_cache" to "authenticated";

grant select on table "public"."invoices_cache" to "authenticated";

grant trigger on table "public"."invoices_cache" to "authenticated";

grant truncate on table "public"."invoices_cache" to "authenticated";

grant update on table "public"."invoices_cache" to "authenticated";

grant delete on table "public"."invoices_cache" to "service_role";

grant insert on table "public"."invoices_cache" to "service_role";

grant references on table "public"."invoices_cache" to "service_role";

grant select on table "public"."invoices_cache" to "service_role";

grant trigger on table "public"."invoices_cache" to "service_role";

grant truncate on table "public"."invoices_cache" to "service_role";

grant update on table "public"."invoices_cache" to "service_role";

grant delete on table "public"."leak_action_assignments" to "anon";

grant insert on table "public"."leak_action_assignments" to "anon";

grant references on table "public"."leak_action_assignments" to "anon";

grant select on table "public"."leak_action_assignments" to "anon";

grant trigger on table "public"."leak_action_assignments" to "anon";

grant truncate on table "public"."leak_action_assignments" to "anon";

grant update on table "public"."leak_action_assignments" to "anon";

grant delete on table "public"."leak_action_assignments" to "authenticated";

grant insert on table "public"."leak_action_assignments" to "authenticated";

grant references on table "public"."leak_action_assignments" to "authenticated";

grant select on table "public"."leak_action_assignments" to "authenticated";

grant trigger on table "public"."leak_action_assignments" to "authenticated";

grant truncate on table "public"."leak_action_assignments" to "authenticated";

grant update on table "public"."leak_action_assignments" to "authenticated";

grant delete on table "public"."leak_action_assignments" to "service_role";

grant insert on table "public"."leak_action_assignments" to "service_role";

grant references on table "public"."leak_action_assignments" to "service_role";

grant select on table "public"."leak_action_assignments" to "service_role";

grant trigger on table "public"."leak_action_assignments" to "service_role";

grant truncate on table "public"."leak_action_assignments" to "service_role";

grant update on table "public"."leak_action_assignments" to "service_role";

grant delete on table "public"."leak_action_state" to "anon";

grant insert on table "public"."leak_action_state" to "anon";

grant references on table "public"."leak_action_state" to "anon";

grant select on table "public"."leak_action_state" to "anon";

grant trigger on table "public"."leak_action_state" to "anon";

grant truncate on table "public"."leak_action_state" to "anon";

grant update on table "public"."leak_action_state" to "anon";

grant delete on table "public"."leak_action_state" to "authenticated";

grant insert on table "public"."leak_action_state" to "authenticated";

grant references on table "public"."leak_action_state" to "authenticated";

grant select on table "public"."leak_action_state" to "authenticated";

grant trigger on table "public"."leak_action_state" to "authenticated";

grant truncate on table "public"."leak_action_state" to "authenticated";

grant update on table "public"."leak_action_state" to "authenticated";

grant delete on table "public"."leak_action_state" to "service_role";

grant insert on table "public"."leak_action_state" to "service_role";

grant references on table "public"."leak_action_state" to "service_role";

grant select on table "public"."leak_action_state" to "service_role";

grant trigger on table "public"."leak_action_state" to "service_role";

grant truncate on table "public"."leak_action_state" to "service_role";

grant update on table "public"."leak_action_state" to "service_role";

grant delete on table "public"."leak_email_log" to "anon";

grant insert on table "public"."leak_email_log" to "anon";

grant references on table "public"."leak_email_log" to "anon";

grant select on table "public"."leak_email_log" to "anon";

grant trigger on table "public"."leak_email_log" to "anon";

grant truncate on table "public"."leak_email_log" to "anon";

grant update on table "public"."leak_email_log" to "anon";

grant delete on table "public"."leak_email_log" to "authenticated";

grant insert on table "public"."leak_email_log" to "authenticated";

grant references on table "public"."leak_email_log" to "authenticated";

grant select on table "public"."leak_email_log" to "authenticated";

grant trigger on table "public"."leak_email_log" to "authenticated";

grant truncate on table "public"."leak_email_log" to "authenticated";

grant update on table "public"."leak_email_log" to "authenticated";

grant delete on table "public"."leak_email_log" to "service_role";

grant insert on table "public"."leak_email_log" to "service_role";

grant references on table "public"."leak_email_log" to "service_role";

grant select on table "public"."leak_email_log" to "service_role";

grant trigger on table "public"."leak_email_log" to "service_role";

grant truncate on table "public"."leak_email_log" to "service_role";

grant update on table "public"."leak_email_log" to "service_role";

grant delete on table "public"."leak_notifications" to "anon";

grant insert on table "public"."leak_notifications" to "anon";

grant references on table "public"."leak_notifications" to "anon";

grant select on table "public"."leak_notifications" to "anon";

grant trigger on table "public"."leak_notifications" to "anon";

grant truncate on table "public"."leak_notifications" to "anon";

grant update on table "public"."leak_notifications" to "anon";

grant delete on table "public"."leak_notifications" to "authenticated";

grant insert on table "public"."leak_notifications" to "authenticated";

grant references on table "public"."leak_notifications" to "authenticated";

grant select on table "public"."leak_notifications" to "authenticated";

grant trigger on table "public"."leak_notifications" to "authenticated";

grant truncate on table "public"."leak_notifications" to "authenticated";

grant update on table "public"."leak_notifications" to "authenticated";

grant delete on table "public"."leak_notifications" to "service_role";

grant insert on table "public"."leak_notifications" to "service_role";

grant references on table "public"."leak_notifications" to "service_role";

grant select on table "public"."leak_notifications" to "service_role";

grant trigger on table "public"."leak_notifications" to "service_role";

grant truncate on table "public"."leak_notifications" to "service_role";

grant update on table "public"."leak_notifications" to "service_role";

grant delete on table "public"."metrics_history" to "anon";

grant insert on table "public"."metrics_history" to "anon";

grant references on table "public"."metrics_history" to "anon";

grant select on table "public"."metrics_history" to "anon";

grant trigger on table "public"."metrics_history" to "anon";

grant truncate on table "public"."metrics_history" to "anon";

grant update on table "public"."metrics_history" to "anon";

grant delete on table "public"."metrics_history" to "authenticated";

grant insert on table "public"."metrics_history" to "authenticated";

grant references on table "public"."metrics_history" to "authenticated";

grant select on table "public"."metrics_history" to "authenticated";

grant trigger on table "public"."metrics_history" to "authenticated";

grant truncate on table "public"."metrics_history" to "authenticated";

grant update on table "public"."metrics_history" to "authenticated";

grant delete on table "public"."metrics_history" to "service_role";

grant insert on table "public"."metrics_history" to "service_role";

grant references on table "public"."metrics_history" to "service_role";

grant select on table "public"."metrics_history" to "service_role";

grant trigger on table "public"."metrics_history" to "service_role";

grant truncate on table "public"."metrics_history" to "service_role";

grant update on table "public"."metrics_history" to "service_role";

grant delete on table "public"."referrals" to "anon";

grant insert on table "public"."referrals" to "anon";

grant references on table "public"."referrals" to "anon";

grant select on table "public"."referrals" to "anon";

grant trigger on table "public"."referrals" to "anon";

grant truncate on table "public"."referrals" to "anon";

grant update on table "public"."referrals" to "anon";

grant delete on table "public"."referrals" to "authenticated";

grant insert on table "public"."referrals" to "authenticated";

grant references on table "public"."referrals" to "authenticated";

grant select on table "public"."referrals" to "authenticated";

grant trigger on table "public"."referrals" to "authenticated";

grant truncate on table "public"."referrals" to "authenticated";

grant update on table "public"."referrals" to "authenticated";

grant delete on table "public"."referrals" to "service_role";

grant insert on table "public"."referrals" to "service_role";

grant references on table "public"."referrals" to "service_role";

grant select on table "public"."referrals" to "service_role";

grant trigger on table "public"."referrals" to "service_role";

grant truncate on table "public"."referrals" to "service_role";

grant update on table "public"."referrals" to "service_role";

grant delete on table "public"."revenue_recovery_events" to "anon";

grant insert on table "public"."revenue_recovery_events" to "anon";

grant references on table "public"."revenue_recovery_events" to "anon";

grant select on table "public"."revenue_recovery_events" to "anon";

grant trigger on table "public"."revenue_recovery_events" to "anon";

grant truncate on table "public"."revenue_recovery_events" to "anon";

grant update on table "public"."revenue_recovery_events" to "anon";

grant delete on table "public"."revenue_recovery_events" to "authenticated";

grant insert on table "public"."revenue_recovery_events" to "authenticated";

grant references on table "public"."revenue_recovery_events" to "authenticated";

grant select on table "public"."revenue_recovery_events" to "authenticated";

grant trigger on table "public"."revenue_recovery_events" to "authenticated";

grant truncate on table "public"."revenue_recovery_events" to "authenticated";

grant update on table "public"."revenue_recovery_events" to "authenticated";

grant delete on table "public"."revenue_recovery_events" to "service_role";

grant insert on table "public"."revenue_recovery_events" to "service_role";

grant references on table "public"."revenue_recovery_events" to "service_role";

grant select on table "public"."revenue_recovery_events" to "service_role";

grant trigger on table "public"."revenue_recovery_events" to "service_role";

grant truncate on table "public"."revenue_recovery_events" to "service_role";

grant update on table "public"."revenue_recovery_events" to "service_role";

grant delete on table "public"."saved_searches" to "anon";

grant insert on table "public"."saved_searches" to "anon";

grant references on table "public"."saved_searches" to "anon";

grant select on table "public"."saved_searches" to "anon";

grant trigger on table "public"."saved_searches" to "anon";

grant truncate on table "public"."saved_searches" to "anon";

grant update on table "public"."saved_searches" to "anon";

grant delete on table "public"."saved_searches" to "authenticated";

grant insert on table "public"."saved_searches" to "authenticated";

grant references on table "public"."saved_searches" to "authenticated";

grant select on table "public"."saved_searches" to "authenticated";

grant trigger on table "public"."saved_searches" to "authenticated";

grant truncate on table "public"."saved_searches" to "authenticated";

grant update on table "public"."saved_searches" to "authenticated";

grant delete on table "public"."saved_searches" to "service_role";

grant insert on table "public"."saved_searches" to "service_role";

grant references on table "public"."saved_searches" to "service_role";

grant select on table "public"."saved_searches" to "service_role";

grant trigger on table "public"."saved_searches" to "service_role";

grant truncate on table "public"."saved_searches" to "service_role";

grant update on table "public"."saved_searches" to "service_role";

grant delete on table "public"."stripe_connection_members" to "anon";

grant insert on table "public"."stripe_connection_members" to "anon";

grant references on table "public"."stripe_connection_members" to "anon";

grant select on table "public"."stripe_connection_members" to "anon";

grant trigger on table "public"."stripe_connection_members" to "anon";

grant truncate on table "public"."stripe_connection_members" to "anon";

grant update on table "public"."stripe_connection_members" to "anon";

grant delete on table "public"."stripe_connection_members" to "authenticated";

grant insert on table "public"."stripe_connection_members" to "authenticated";

grant references on table "public"."stripe_connection_members" to "authenticated";

grant select on table "public"."stripe_connection_members" to "authenticated";

grant trigger on table "public"."stripe_connection_members" to "authenticated";

grant truncate on table "public"."stripe_connection_members" to "authenticated";

grant update on table "public"."stripe_connection_members" to "authenticated";

grant delete on table "public"."stripe_connection_members" to "service_role";

grant insert on table "public"."stripe_connection_members" to "service_role";

grant references on table "public"."stripe_connection_members" to "service_role";

grant select on table "public"."stripe_connection_members" to "service_role";

grant trigger on table "public"."stripe_connection_members" to "service_role";

grant truncate on table "public"."stripe_connection_members" to "service_role";

grant update on table "public"."stripe_connection_members" to "service_role";

grant delete on table "public"."subscription_history" to "anon";

grant insert on table "public"."subscription_history" to "anon";

grant references on table "public"."subscription_history" to "anon";

grant select on table "public"."subscription_history" to "anon";

grant trigger on table "public"."subscription_history" to "anon";

grant truncate on table "public"."subscription_history" to "anon";

grant update on table "public"."subscription_history" to "anon";

grant delete on table "public"."subscription_history" to "authenticated";

grant insert on table "public"."subscription_history" to "authenticated";

grant references on table "public"."subscription_history" to "authenticated";

grant select on table "public"."subscription_history" to "authenticated";

grant trigger on table "public"."subscription_history" to "authenticated";

grant truncate on table "public"."subscription_history" to "authenticated";

grant update on table "public"."subscription_history" to "authenticated";

grant delete on table "public"."subscription_history" to "service_role";

grant insert on table "public"."subscription_history" to "service_role";

grant references on table "public"."subscription_history" to "service_role";

grant select on table "public"."subscription_history" to "service_role";

grant trigger on table "public"."subscription_history" to "service_role";

grant truncate on table "public"."subscription_history" to "service_role";

grant update on table "public"."subscription_history" to "service_role";

grant delete on table "public"."subscriptions_cache" to "anon";

grant insert on table "public"."subscriptions_cache" to "anon";

grant references on table "public"."subscriptions_cache" to "anon";

grant select on table "public"."subscriptions_cache" to "anon";

grant trigger on table "public"."subscriptions_cache" to "anon";

grant truncate on table "public"."subscriptions_cache" to "anon";

grant update on table "public"."subscriptions_cache" to "anon";

grant delete on table "public"."subscriptions_cache" to "authenticated";

grant insert on table "public"."subscriptions_cache" to "authenticated";

grant references on table "public"."subscriptions_cache" to "authenticated";

grant select on table "public"."subscriptions_cache" to "authenticated";

grant trigger on table "public"."subscriptions_cache" to "authenticated";

grant truncate on table "public"."subscriptions_cache" to "authenticated";

grant update on table "public"."subscriptions_cache" to "authenticated";

grant delete on table "public"."subscriptions_cache" to "service_role";

grant insert on table "public"."subscriptions_cache" to "service_role";

grant references on table "public"."subscriptions_cache" to "service_role";

grant select on table "public"."subscriptions_cache" to "service_role";

grant trigger on table "public"."subscriptions_cache" to "service_role";

grant truncate on table "public"."subscriptions_cache" to "service_role";

grant update on table "public"."subscriptions_cache" to "service_role";

grant delete on table "public"."sync_logs" to "anon";

grant insert on table "public"."sync_logs" to "anon";

grant references on table "public"."sync_logs" to "anon";

grant select on table "public"."sync_logs" to "anon";

grant trigger on table "public"."sync_logs" to "anon";

grant truncate on table "public"."sync_logs" to "anon";

grant update on table "public"."sync_logs" to "anon";

grant delete on table "public"."sync_logs" to "authenticated";

grant insert on table "public"."sync_logs" to "authenticated";

grant references on table "public"."sync_logs" to "authenticated";

grant select on table "public"."sync_logs" to "authenticated";

grant trigger on table "public"."sync_logs" to "authenticated";

grant truncate on table "public"."sync_logs" to "authenticated";

grant update on table "public"."sync_logs" to "authenticated";

grant delete on table "public"."sync_logs" to "service_role";

grant insert on table "public"."sync_logs" to "service_role";

grant references on table "public"."sync_logs" to "service_role";

grant select on table "public"."sync_logs" to "service_role";

grant trigger on table "public"."sync_logs" to "service_role";

grant truncate on table "public"."sync_logs" to "service_role";

grant update on table "public"."sync_logs" to "service_role";

grant delete on table "public"."team_members" to "anon";

grant insert on table "public"."team_members" to "anon";

grant references on table "public"."team_members" to "anon";

grant select on table "public"."team_members" to "anon";

grant trigger on table "public"."team_members" to "anon";

grant truncate on table "public"."team_members" to "anon";

grant update on table "public"."team_members" to "anon";

grant delete on table "public"."team_members" to "authenticated";

grant insert on table "public"."team_members" to "authenticated";

grant references on table "public"."team_members" to "authenticated";

grant select on table "public"."team_members" to "authenticated";

grant trigger on table "public"."team_members" to "authenticated";

grant truncate on table "public"."team_members" to "authenticated";

grant update on table "public"."team_members" to "authenticated";

grant delete on table "public"."team_members" to "service_role";

grant insert on table "public"."team_members" to "service_role";

grant references on table "public"."team_members" to "service_role";

grant select on table "public"."team_members" to "service_role";

grant trigger on table "public"."team_members" to "service_role";

grant truncate on table "public"."team_members" to "service_role";

grant update on table "public"."team_members" to "service_role";

grant delete on table "public"."teams" to "anon";

grant insert on table "public"."teams" to "anon";

grant references on table "public"."teams" to "anon";

grant select on table "public"."teams" to "anon";

grant trigger on table "public"."teams" to "anon";

grant truncate on table "public"."teams" to "anon";

grant update on table "public"."teams" to "anon";

grant delete on table "public"."teams" to "authenticated";

grant insert on table "public"."teams" to "authenticated";

grant references on table "public"."teams" to "authenticated";

grant select on table "public"."teams" to "authenticated";

grant trigger on table "public"."teams" to "authenticated";

grant truncate on table "public"."teams" to "authenticated";

grant update on table "public"."teams" to "authenticated";

grant delete on table "public"."teams" to "service_role";

grant insert on table "public"."teams" to "service_role";

grant references on table "public"."teams" to "service_role";

grant select on table "public"."teams" to "service_role";

grant trigger on table "public"."teams" to "service_role";

grant truncate on table "public"."teams" to "service_role";

grant update on table "public"."teams" to "service_role";


drop policy if exists "leak_action_state_select_own" on "public"."leak_action_state";
  create policy "leak_action_state_select_own"
  on "public"."leak_action_state"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));



drop policy if exists "leak_action_state_upsert_own" on "public"."leak_action_state";
  create policy "leak_action_state_upsert_own"
  on "public"."leak_action_state"
  as permissive
  for all
  to public
using ((auth.uid() = user_id))
with check ((auth.uid() = user_id));



drop policy if exists "leak_notifications_select_own" on "public"."leak_notifications";
  create policy "leak_notifications_select_own"
  on "public"."leak_notifications"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));



drop policy if exists "leak_notifications_update_own" on "public"."leak_notifications";
  create policy "leak_notifications_update_own"
  on "public"."leak_notifications"
  as permissive
  for update
  to public
using ((auth.uid() = user_id))
with check ((auth.uid() = user_id));



drop policy if exists "Users can view their saved searches" on "public"."saved_searches";
  create policy "Users can view their saved searches"
  on "public"."saved_searches"
  as permissive
  for all
  to public
using ((auth.uid() = user_id));



drop policy if exists "scm_select_own" on "public"."stripe_connection_members";
  create policy "scm_select_own"
  on "public"."stripe_connection_members"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));



drop policy if exists "Users can view their team memberships" on "public"."team_members";
  create policy "Users can view their team memberships"
  on "public"."team_members"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));


DROP TRIGGER IF EXISTS update_churn_predictions_timestamp ON public.churn_predictions;
CREATE TRIGGER update_churn_predictions_timestamp BEFORE UPDATE ON public.churn_predictions FOR EACH ROW EXECUTE FUNCTION public.update_churn_prediction_timestamp();

DROP TRIGGER IF EXISTS update_feature_flags_updated_at ON public.feature_flags;
CREATE TRIGGER update_feature_flags_updated_at BEFORE UPDATE ON public.feature_flags FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_saas();

DROP TRIGGER IF EXISTS update_teams_updated_at ON public.teams;
CREATE TRIGGER update_teams_updated_at BEFORE UPDATE ON public.teams FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_saas();


